version: '3'

networks:
  backend:

services:
  traefik:
    image: traefik:v2.3.6
    restart: always
    command:
      - --accesslog
      - --api.insecure=true
      - --providers.docker
      - --providers.docker.exposedbydefault=false
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 80:80
      - 443:443
      - 8080:8080
  
  wordpress:
    build: .
    depends_on:
      - mysql
    restart: always
    volumes:
        - ./Content/:/var/www/html/wp-content/
    environment:
      - WORDPRESS_DB_HOST=${DB_HOST}
      - WORDPRESS_DB_USER=${DB_USER}
      - WORDPRESS_DB_NAME=${DB_NAME}
      - WORDPRESS_DB_PASSWORD=${DB_PASS}
      - WORDPRESS_DEBUG=${DEV_MODE}
      - |
          WORDPRESS_CONFIG_EXTRA=
          define('WP_HOME','http://${URL}');
          define('WP_SITEURL','http://${URL}');
          define('WP_CACHE', true);
          define('WP_REDIS_HOST', 'redis');
          define('WP_REDIS_PORT', '6379');
          define('WP_CACHE_KEY_SALT', '${URL}' );
          require_once( '/var/www/html/wp-content/vendor/autoload.php' );
          (new \Whoops\Run)->pushHandler(new \Whoops\Handler\PrettyPageHandler);
          (new \Whoops\Run)->register();
    expose:
      - 80
      - 443
    labels:
      - traefik.enable=true
      - traefik.protocol=https
      - traefik.http.routers.wordpress.rule=Host(`${URL}`)
      - trarfik.http.routers.wordpress.tls=true

  mysql:
    image: ${MYSQL_IMAGE}
    restart: always
    volumes:
      - ./DB/:/docker-entrypoint-initdb.d
    environment:
      - MYSQL_DATABASE=wordpress
      - MYSQL_ROOT_PASSWORD=password
  
  redis:
    image: redis:6
    restart: always
    ports:
      - "6379:6379"
    entrypoint: redis-server
    labels:
      - traefik.enable=true
    
volumes:
    db_data: {}